version: '3.8'

services:
  web:
    image: python:3.9-slim
    volumes:
      - ./build/web:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - "5555:5555"
    command: python3 -m http.server 5555